### ISSUE TITLE
Is pinning to isosplit5==0.1.3 necessary?

### ISSUE THREAD

**Issue by rly** [magland/mountainsort4#10]
https://github.com/magland/mountainsort4/blob/1a27355fec63e7eb6cf4571978e5d08a8f4b89f2/setup.py#L9

isosplit5 0.2.0+ includes this fix https://github.com/magland/isosplit5_python/pull/8 which installs pybind11 before setup.

I suspect this might also fix #7 (and the OP in #6 mentioned that installing isosplit5 from source fixed a similar issue) but I am not sure because that might just be a windows thing.

**Comment by magland** [comment]
Oh I didn't realize it was pinned. I guess I should put it as >=0.2.0? I don't anticipate developing isosplit5 any further since there is now isosplit6. But also it would **not** be wise to move to isosplit6 for mountainsort4 since there were changes in the implementation.

**Comment by rly** [comment]
I think >=0.2.0 would be good. Installing mountainsort4 naively (`pip install mountainsort4`) fails on my mac because pybind11 isn't installed first, and I think updating this requirement would fix that. Super minor, because I think most people will/should use the newer mountainsort, but I need to use mountainsort4 to reproduce some older results.

**Comment by rly** [comment]
(I can get around this issue easily - just thought I would help the next person who might encounter this!)

**Comment by magland** [comment]
Okay this is done. mountainsort4 1.0.6 on pypi. Thanks @rly

**Comment by rly** [comment]
Thank you! `pip install mountainsort4` works like a charm now.
